ALTER TABLE bots
  ADD COLUMN IF NOT EXISTS start_welcome_message TEXT,
  ADD COLUMN IF NOT EXISTS start_show_menu_only BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS start_show_tip BOOLEAN NOT NULL DEFAULT TRUE;
